package com.senac.assister.backend.domain.service;

import com.google.cloud.storage.Acl;
import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import com.google.common.io.Files;
import com.senac.assister.backend.domain.entity.Customer;
import com.senac.assister.backend.domain.exception.InvalidImageExtensionException;
import com.senac.assister.backend.domain.security.Hash;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.*;
import java.util.ArrayList;
import java.util.Collections;

@Service
public class ImageServiceImpl implements ImageService {

    private static Storage storage;

    @Value("${GCP_BUCKET}")
    private String bucketName;

    public ImageServiceImpl() {
    }

    /**
     * Upload to GCP Storage Bucket on pi4-assister project using credentials as environment variable. File name is
     * generated by us on variable GeneratedImageName. The Hash is the Person Identifier + CreatedAt. File name will be
     * the same for same user, GCP will override the existing one.
     * @param file
     * @param customer
     * @return url file if success, otherwise throws a exception.
     */
    @Override
    public String upload(MultipartFile file, Customer customer) {
        String imageExtension = validateImageExtension(file.getOriginalFilename());

        validateCredentials();

        String generatedImageName = Hash.convertToMd5(customer.getPersonIdentifier() + customer.getCreatedAt()) + imageExtension;

        File convertedFile = convertMultiPartToFile(file);

        try {
            BlobInfo blobInfo = storage
                    .create(BlobInfo
                                    .newBuilder(bucketName, generatedImageName)
                                    .setAcl(new ArrayList<>(
                                            Collections.singletonList(
                                                    Acl.of(Acl.User.ofAllUsers(),
                                                            Acl.Role.READER)))).build(),
                            Files.toByteArray(convertedFile));
            return blobInfo.getMediaLink();
        } catch (IOException e) {
            throw new RuntimeException("Error on uploading image.");
        }
    }

    private File convertMultiPartToFile(MultipartFile file) {
        File convertedFile = new File(file.getOriginalFilename());

        try (FileOutputStream stream = new FileOutputStream(convertedFile)) {
            stream.write(file.getBytes());
        } catch (IOException e) {
            throw new RuntimeException("Error converting image.");
        }

        return convertedFile;
    }

    private String validateImageExtension(String fileName) {
        if (!fileName.matches("([^\\s]+(\\.(?i)(jpe?g|png))$)")) {
            throw new InvalidImageExtensionException(fileName);
        }
        return fileName.substring(fileName.lastIndexOf("."));
    }

    private void validateCredentials() {
        storage = StorageOptions.getDefaultInstance().getService();
    }
}
